version: "3"
services:
  db:
    image: "postgres:15.2"
    container_name: "node-gmp-db"
    restart: always
    environment:
      - POSTGRES_USER=${DB_APP_USER}
      - POSTGRES_PASSWORD=${DB_APP_PASSWORD}
      - POSTGRES_DB=${DB_APP_NAME}
    ports:
      - 5432:5432
    networks:
      - express-network
    volumes:
      - postgres_db:/var/lib/postgresql/data
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - express-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  api:
    depends_on:
      - db
    restart: always
    build: .
    ports: 
      - "3000:3000"
    networks:
      - express-network
    volumes:
      - server-data:/var/lib/server
volumes:
  postgres_db:
    driver: local
  pgadmin-data:
    driver: local
  server-data:
    driver: local

networks:
  express-network: 